export const VALIDATION_LIMITS = {
  PROMPT_MAX_LENGTH: 500,
  SCRIPT_MAX_LENGTH: 1250,
  NUMBER_OF_IMAGE_PROMPTS: 3,
} as const;

export const TIMEOUT_LIMITS = {
  MIDJOURNEY_INITIAL_TIMEOUT: 5 * 60 * 1000, // 5 minutes
  MIDJOURNEY_PROGRESS_TIMEOUT: 5 * 60 * 1000, // 5 minutes
} as const;

export const CONCURRENCY_LIMITS = {
  MIDJOURNEY_MAX_CONCURRENT_NEW_JOBS: 2,
  MIDJOURNEY_MAX_CONCURRENT_RESUMING_JOBS: 1,
} as const;

export const APP_LIMITS = {
  MAX_RERENDERS: 5,
  MAX_DOWNLOADS: 10,
} as const;
